### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by kroggen** [aergoio/web-ide#1]
It is not possible to deploy a smart contract using the web IDE due to CORS issue.

Tested on Chrome, Brave and Safari. The same problem on all.

**Comment by kroggen** [comment]
@ultrafellen

**Comment by ultrafellen** [comment]
Let me check this issue. Thanks for the report.

**Comment by ultrafellen** [comment]
The issue has been resolved.

**Comment by kroggen** [comment]
It worked! Thank you
